<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ffa036cb-ac32-4383-a645-13feca6cd153</UserSecretsId>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>True</SignAssembly>
  </PropertyGroup>

  <!--<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>-->
  <!--<PropertyGroup> 
    <WarningsAsErrors>1591</WarningsAsErrors>
    --><!-- Treat warning 1591 as error --><!--
  </PropertyGroup>-->
  <PropertyGroup>
    <OutputPath Condition="'$(Configuration)' == 'Debug'">$(ProjectDir)bin\Debug\net8.0\</OutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">$(ProjectDir)bin\Release\net8.0\</OutputPath>
  </PropertyGroup>
  <Target Name="AutoBuildAndPublish" BeforeTargets="Publish">
    <Exec Command="dotnet build --configuration Release" />
  </Target>

  <Target Name="CopyPublishedFiles" AfterTargets="Publish">
    <ItemGroup>
      <PublishedFiles Include="$(PublishDir)**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(PublishedFiles)" DestinationFolder="C:\lakshaman\Source\lakshamanr\mssql\src\WebClient\mssql.client\electron\API\" />
  </Target>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.8" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenIddict" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Client" Version="7.1.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.1.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore.Models" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Quartz" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Server" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Validation" Version="7.1.0" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.1.0" />
    <PackageReference Include="Quartz" Version="3.15.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.0" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="certificates\" />
  </ItemGroup>

</Project>
